name: Deploy Wanton

env:
  NAME: wanpm
  ACTOR: ${{ github.actor }}
  REPO: ${{ github.repository }}
  DOCKER_IMAGE: ghcr.io/hwanbin/wanpm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Display Go Version
        run: go version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Get Git Tag
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Build Docker Image
        run: |
          set -e
          docker build -t ${{ env.DOCKER_IMAGE }}:latest -t ${{ env.DOCKER_IMAGE }}:${{ env.TAG }} .
      - name: Push Latest Image to GHCR
        run: |
          set -e
          docker push ${{ env.DOCKER_IMAGE }}:latest
      - name: Push Versioned Image to GHCR
        run: |
          set -e
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Check Container Existence
        id: check_container
        run: |
          if [ "$(docker ps -a -q -f name=${{ env.NAME }})" ]; then
            echo "container_exists=true" >> $GITHUB_ENV
          else
            echo "container_exists=false" >> $GITHUB_ENV
          fi
      - name: Delete Old Container
        if: env.container_exists == 'true'
        run: docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }}
      - name: Check Old Image
        run: |
          if docker image inspect ${{ env.DOCKER_IMAGE }}:latest > /dev/null 2>&1; then
            echo "image_exists=true" >> $GITHUB_ENV
          else
            echo "image_exists=false" >> $GITHUB_ENV
          fi
      - name: Delete Old Image
        if: env.image_exists == 'true'
        run: docker rmi ${{ env.DOCKER_IMAGE }}:latest
      - name: Authenticate to GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ env.ACTOR }} --password-stdin
      - name: Pull Docker Image
        run: docker pull ${{ env.DOCKER_IMAGE }}:latest
      - name: Run Docker Container
        run: docker run -d -p 9000:9000 -e MAPBOX_GEOCODE_TOKEN=$MAPBOX_GEOCODE_TOKEN -e S3_BUCKET_NAME=$S3_BUCKET_NAME -e WANTONI_DB_DSN=$WANTONI_DB_DSN -v ~/.aws:/root/.aws --name ${{ env.NAME }} --restart unless-stopped ${{ env.DOCKER_IMAGE }}:latest