name: Deploy Wantoni

env:
  NAME: wantoni
  DOCKER_IMAGE: wantonium/wantoni

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Display Go Version
        run: go version
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t wantonium/wantoni:0.0.1 .
      - name: Push Image to Docker Hub
        run: docker push wantonium/wantoni:0.0.1
  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Check Container Existence
        id: check_container
        run: |
          if [ "$(docker ps -a -q -f name=${{ env.NAME }})" ]; then
            echo "container_exists=true" >> $GITHUB_ENV
          else
            echo "container_exists=false" >> $GITHUB_ENV
          fi
      - name: Delete Old Container
        if: env.container_exists == 'true'
        run: docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }}
      - name: Check Old Image
        run: |
          if docker image inspect ${{ env.DOCKER_IMAGE }}:0.0.1 > /dev/null 2>&1; then
            echo "image_exists=true" >> $GITHUB_ENV
          else
            echo "image_exists=false" >> $GITHUB_ENV
          fi
      - name: Delete Old Image
        if: env.image_exists == 'true'
        run: docker rmi ${{ env.DOCKER_IMAGE }}:0.0.1
      - name: Pull Docker Image
        run: docker pull ${{ env.DOCKER_IMAGE }}:0.0.1
      - name: Run Docker Container
        run: docker run -d -p 9000:9000 -e MAPBOX_GEOCODE_TOKEN=$MAPBOX_GEOCODE_TOKEN -e S3_BUCKET_NAME=$S3_BUCKET_NAME -e WANTONI_DB_DSN=$WANTONI_DB_DSN -v ~/.aws:/root/.aws --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:0.0.1